stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: "us-west-2"
  EKS_CLUSTER_NAME: "voting-app"
  K8S_MANIFEST_PATH: "k8s-specifications/"

before_script:
  - echo "Configuring AWS CLI..."
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_DEFAULT_REGION
  - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME

deploy:
  stage: deploy
  script:
    - kubectl apply -f $K8S_MANIFEST_PATH
    - echo "Deployment completed!"
